# the name by which the project can be referenced within Serena
project_name: "my-project"

# list of languages for which language servers are started
languages:
- typescript

# the encoding used by text files in the project
encoding: "utf-8"
